# $Id$

.include "Makefile.inc"

.include <cthru.defs.mk>


CC_LANG = C90

SRCS += stping.c
SRCS += common.c

.include <cthru.obj.mk>


PROG = stping

.if "${UNAME}" == "Linux"
PROG_LDFLAGS += -lm
.endif

.include <cthru.prog.mk>

