# $Id$

.include "Makefile.inc"

.include <cthru.defs.mk>


CC_LANG = C90

SRCS += dgpingd.c
SRCS += common.c

# For confusing struct sockaddr_in sin; with sin() from math.h
CFLAGS := ${CFLAGS:N-Wshadow}
CFLAGS += -Wshadow

.include <cthru.obj.mk>


PROG = dgpingd

.include <cthru.prog.mk>

